management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httptrace, busrefresh

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: local

  cloud:
    config:
      name: damda-user

  config:
    import: optional:configserver:http://127.0.0.1:8888/
#    import: optional:configserver:http://damda-config:8888/
#    import: configserver:http://ec2-13-124-159-0.ap-northeast-2.compute.amazonaws.com:8888/

logging:
  level:
    kr.co.damdauser.service.client: DEBUG
